name: Top GitHub Users of Sri Lanka
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  find_top_users:
    name: Find Top GitHub Users
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Find Top GitHub Users
        uses: DARKDRAGON-LK/top-github-users-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_EMAIL: ${{ secrets.EMAIL }}
          GIT_NAME: ${{ secrets.NAME }}
      
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update top GitHub users"
          git push
