name: Top GitHub Users of Sri Lanka
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  find_top_users:
    name: Find Top GitHub Users
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Find Top GitHub Users
        run: npm run find-top-users
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
      
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update top GitHub users"
          git push
